version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: root
    networks:
      - MyMonitor
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - "/home/bogdanov/grafana/data:/var/lib/grafana"
      - "/home/bogdanov/grafana/datasources:/etc/grafana/datasources"
      - "/home/bogdanov/grafana/dashboards:/etc/grafana/dashboards"
      - "/home/bogdanov/grafana/plugins:/var/lib/grafana/plugins"
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    #command:
    #  - "--config.file=/etc/prometheus/prometheus.yml"
    #  - "--storage.tsdb.path=/prometheus"
    #  - "--web.console.libraries=/etc/prometheus/console_libraries"
    #  - "--web.console.templates=/etc/prometheus/consoles"
    #  - "--storage.tsdb.retention.time=200h"
    #  - "--web.enable-lifecycle"
    networks:
      - MyMonitor
    user: root
    ports:
      - 9090:9090
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - "/home/bogdanov/prometeus/data:/prometheus"
      - "/home/bogdanov/prometeus/conf:/etc/prometheus"
networks:
  MyMonitor:
    driver: bridge
    name: MyMonitor
